module.exports = {
	up: async (queryInterface, Sequelize) => {
		console.log('Seeds for Media START...')
		await queryInterface.bulkInsert("Media", [
			{
				fileName: "3790532890_bf58d30b56_b.jpg",
				articleId: 1,
				type: "image",
				src: "https://live.staticflickr.com/2631/3790532890_bf58d30b56_b.jpg",
				order: 1,
				isPhysicallyExist: "yes",
				publishStatus: "published",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				fileName: "7281444204_296c94d45d_b.jpg",
				articleId: 2,
				type: "image",
				src: "https://live.staticflickr.com/7093/7281444204_296c94d45d_b.jpg",
				order: 1,
				isPhysicallyExist: "yes",
				publishStatus: "draft",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				fileName: "photo-1667986292516-f27450ae75a9.jpg",
				articleId: 3,
				type: "image",
				src: "https://images.unsplash.com/photo-1667986292516-f27450ae75a9?q=80&w=388&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
				order: 1,
				isPhysicallyExist: "yes",
				publishStatus: "draft",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				fileName: "photo-1593377202145-c5e97fd065f4.jpg",
				articleId: 4,
				type: "image",
				src: "https://images.unsplash.com/photo-1593377202145-c5e97fd065f4?q=80&w=386&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
				order: 1,
				isPhysicallyExist: "yes",
				publishStatus: "draft",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				fileName: "robots-800x523.jpg",
				articleId: 5,
				type: "image",
				src: "https://image.cnbcfm.com/api/v1/image/105786247-1552311939465gettyimages-920743046.jpeg?v=1562950112&w=1480&h=833&ffmt=webp&vtcrop=y",
				order: 1,
				isPhysicallyExist: "yes",
				publishStatus: "draft",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				fileName: "The_Future_of_Robotics.jpg",
				articleId: 6,
				type: "image",
				src: "https://www.simplilearn.com/ice9/free_resources_article_thumb/The_Future_of_Robotics.jpg",
				order: 1,
				isPhysicallyExist: "yes",
				publishStatus: "draft",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				fileName:
					"rs-202131-maxresdefault.jpg?w=1581&h=1054&crop=1.jpg",
				articleId: 7,
				type: "image",
				src: "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-202131-maxresdefault.jpg?w=1581&h=1054&crop=1",
				order: 1,
				isPhysicallyExist: "yes",
				publishStatus: "draft",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				fileName: "1*ynxCgSa2MP8y5p2R3DNr6Q.png",
				articleId: 8,
				type: "image",
				src: "https://miro.medium.com/v2/resize:fit:1000/1*ynxCgSa2MP8y5p2R3DNr6Q.png",
				order: 1,
				isPhysicallyExist: "yes",
				publishStatus: "draft",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				fileName: "9",
				articleId: 9,
				type: "image",
				src: "https://media.hswstatic.com/eyJidWNrZXQiOiJjb250ZW50Lmhzd3N0YXRpYy5jb20iLCJrZXkiOiJnaWZcL3JvYm90cy0yLmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6ODI4fSwidG9Gb3JtYXQiOiJhdmlmIn19",
				order: 1,
				isPhysicallyExist: "yes",
				publishStatus: "draft",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				fileName: "10",
				articleId: 10,
				type: "image",
				src: "https://media.hswstatic.com/eyJidWNrZXQiOiJjb250ZW50Lmhzd3N0YXRpYy5jb20iLCJrZXkiOiJnaWZcL3JvYm90cy0zLmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6ODI4fSwidG9Gb3JtYXQiOiJhdmlmIn19",
				order: 1,
				isPhysicallyExist: "yes",
				publishStatus: "draft",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				fileName: "11",
				articleId: 11,
				type: "image",
				src: "https://media.hswstatic.com/eyJidWNrZXQiOiJjb250ZW50Lmhzd3N0YXRpYy5jb20iLCJrZXkiOiJnaWZcL3JvYm90cy00LmpwZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6ODI4fSwidG9Gb3JtYXQiOiJhdmlmIn19",
				order: 1,
				isPhysicallyExist: "yes",
				publishStatus: "draft",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				fileName: "11",
				articleId: 11,
				type: "image",
				src: "https://www.theengineer.co.uk/media/xzmi1c1k/humanoid-robot_adobestock_632195730.jpg?width=800&height=450&format=webp&quality=80&bgcolor=White&v=1da077cfcbc02d0",
				order: 1,
				isPhysicallyExist: "yes",
				publishStatus: "draft",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				fileName: "12",
				articleId: 12,
				type: "image",
				src: "https://www.theengineer.co.uk/media/z23d0hdh/apptronik-apollo-1.png?width=800&height=450&format=webp&quality=80&bgcolor=White&v=1dad10ca82f3610",
				order: 1,
				isPhysicallyExist: "yes",
				publishStatus: "draft",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				fileName: "13",
				articleId: 13,
				type: "image",
				src: "https://www.currencytransfer.com/wp-content/uploads/2022/10/robot-3-edit.min_.jpg",
				order: 1,
				isPhysicallyExist: "yes",
				publishStatus: "draft",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				fileName: "14",
				articleId: 14,
				type: "image",
				src: "https://www.currencytransfer.com/wp-content/uploads/2022/10/robot-2-edit.min_.jpg",
				order: 1,
				isPhysicallyExist: "yes",
				publishStatus: "draft",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				fileName: "15",
				articleId: null,
				type: "image",
				src: "https://admissions.rochester.edu/blog/wp-content/uploads/2015/08/test.png",
				order: 1,
				isPhysicallyExist: "yes",
				publishStatus: "published",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				fileName: "16",
				articleId: null,
				type: "image",
				src: "https://daily.jstor.org/wp-content/uploads/2015/05/standardizedtests.jpg",
				order: 1,
				isPhysicallyExist: "yes",
				publishStatus: "published",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
		]);
		console.log('Seeds for Media END...')
	},

	down: async (queryInterface, Sequelize) => {
		return queryInterface.bulkDelete("Media", null, {});
	},
};
